<a href="https://colab.research.google.com/github/ergonrizky26/habis-kerja-data-science-practice/blob/DS001/%5BModul_5_Habis_Kerja%5D_python_data_modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modul 5 - Membahas mengenai Modelling dengan Python
Berikut ini adalah daftar isi dari Notebook ini :
1. Data Preparation
2. Finding Data Insight
3. Data Manipulation
4. Modelling Preparation
5. Modelling
6. Modelling Evaluation

## 1. Data Preparation

### Import Packages

In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# import sklearn libraries
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import KMeans

### Data Overview

In [113]:
data_path = os.path.join("drive","MyDrive","Titanic", "train.csv")
print(data_path)

drive/MyDrive/Titanic/train.csv

In [114]:
data = pd.read_csv(data_path)

In [115]:
# Check jumlah baris (records) dan jumlah kolom
data.shape # Outputnya adalah (baris, kolom)

(891, 12)

**Keterangan data : **
1. PassengerId : id dari records/penumpang
2. Survived : Catatan bahwa dia selamat atau meninggal(1=selamat/0=meinggal)
3. Pclass : Kelas dari penumpang
4. Name : Nama penumpang
5. Sex : Jenis kelamin penumpang
6. Age : Usia penumpang
7. SibSp : Jumlah Siblings/Spouse (saudara atau pasangan)
8. Parch : Jumlah Parent/Children (Orangtua atau anak)
9. Ticket : Nomor Tiket
10. Fare : Harga Tiket
11. Cabin : Posisi duduk/kabin penumpang
12. Embarked : Pelabuhan tempat penumpang berangkat

In [116]:
# Melihat overview data (top 5 teratas)
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [117]:
# Melihat overview data (top 5 terbawah)
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [118]:
# Melihat overview data (random 5 data)
data.sample(5, random_state=91) # random_state agar ketika di run datanya tidak berubah-ubah

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.0,0,2,F.C.C. 13529,26.2500,NaN,S
561,562,0,3,"Sivic, Mr. Husein",male,40.0,0,0,349251,7.8958,NaN,S
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.0,0,2,113503,211.5000,C82,C
636,637,0,3,"Leinonen, Mr. Antti Gustaf",male,32.0,0,0,STON/O 2. 3101292,7.9250,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C

In [119]:
# Melihat tipe data dari masing-masing kolom dan jumlah baris/records yang kosong
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Data Quality Check

In [120]:
# Check nilai-nilai yang ada di suatu kolom
# data['nama_kolom'].unique()
data["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [121]:
# Melihat persebaran data (min, max, quantile)
# data.describe() -> untuk data numeric
data.describe(include=['O']) # untuk data categoric

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [122]:
# Melihat apakah ada kolom yang nilainya kosong
data.isnull().sum() # Melihat jumlah variabel yang kosong

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [123]:
data.isna().mean() * 100 # Persentase baris yang kosong dari keseluruhan

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

### Handling Missing values

In [124]:
# Drop records atau baris
data_dropped = data.dropna()
data_dropped.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [125]:
data.shape, data_dropped.shape

((891, 12), (183, 12))

In [126]:
# Drop variable atau kolom
data_dropped = data.drop(columns=['Cabin'], axis=1)
data_dropped.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [127]:
data.shape, data_dropped.shape

((891, 12), (891, 11))

In [128]:
# Mengisi records atau baris
# Data_dropped = data_dropped.fillna(0)
data_dropped['Embarked_filled'] = data_dropped['Embarked'].fillna('Kosong') # Atau missing

In [129]:
data_dropped.loc[data_dropped['Embarked'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Embarked_filled
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,NaN,Kosong
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,NaN,Kosong

In [130]:
data_dropped['Age'] = data_dropped['Age'].fillna(method='ffill')
data_dropped['Age'] = data_dropped['Age'].fillna(method='bfill')
data_dropped['Age'] = data_dropped['Age'].fillna(data_dropped['Age'].mean())

data_dropped['Embarked'] = data_dropped['Embarked'].fillna(data_dropped['Embarked'].value_counts().idxmax())

In [131]:
data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PassengerId      891 non-null    int64
 1   Survived         891 non-null    int64
 2   Pclass           891 non-null    int64
 3   Name             891 non-null    object
 4   Sex              891 non-null    object
 5   Age              891 non-null    float64
 6   SibSp            891 non-null    int64
 7   Parch            891 non-null    int64
 8   Ticket           891 non-null    object
 9   Fare             891 non-null    float64
 10  Embarked         891 non-null    object
 11  Embarked_filled  891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Handling Duplicated Values

In [132]:
data = data.append(data.loc[1], ignore_index=True)

<ipython-input-132-c64219dc7576>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(data.loc[1], ignore_index=True)

In [133]:
# Check baris yang duplikat
data.loc[data['Name'].duplicated()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
891,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [134]:
# Membuang baris duplikat semuanya
data.drop_duplicates(keep=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [135]:
# Membuang baris duplikat semua, kecuali paling atas
data.drop_duplicates(keep='first')

# Membuang baris duplikat semua, kecuali paling bawah
data.drop_duplicates(keep='last')

# Membuang baris duplikat berdasarkan beberapa kolom
data.drop_duplicates(subset=['Name','Sex'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## 2. Finding Data Insight

In [136]:
# aggregat data berdasarkan suatu kolom
# data.groupby('Kelas).mean()[['Nilai]]
data.groupby('Embarked').mean()[['Age']]

<ipython-input-136-8e9e8134b801>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby('Embarked').mean()[['Age']]

                Age
Embarked
C         30.869618
Q         28.089286
S         29.445397

In [137]:
# menghitung hubungan antara dua variable
# pd.crosstab(data['Kelas'], data['Ikut Bimbel'])
pd.crosstab(data['Sex'], data['Embarked'], normalize=True) # normalize value data/mengetahui persentasi suatu data
# pd.crosstab(data['Sex'], data['Embarked'])

Embarked         C         Q         S
Sex
female    0.083146  0.040449  0.228090
male      0.106742  0.046067  0.495506

## 3. Data Manipulation

### Binnning

In [138]:
# membagi data sesuai quantilnya
# arti dari '(' berarti esklusif (nilai tidak diikutkan)
# arti dari ']' berarti inklusif (nilai diikutkan)
pd.qcut(data['Age'], 5)

0       (19.0, 25.0]
1       (32.0, 41.0]
2       (25.0, 32.0]
3       (32.0, 41.0]
4       (32.0, 41.0]
           ...
887    (0.419, 19.0]
888              NaN
889     (25.0, 32.0]
890     (25.0, 32.0]
891     (32.0, 41.0]
Name: Age, Length: 892, dtype: category
Categories (5, interval[float64, right]): [(0.419, 19.0] < (19.0, 25.0] < (25.0, 32.0] <
                                           (32.0, 41.0] < (41.0, 80.0]]

In [139]:
pd.qcut(data['Age'], 5).value_counts()

(0.419, 19.0]    164
(25.0, 32.0]     145
(41.0, 80.0]     142
(19.0, 25.0]     137
(32.0, 41.0]     127
Name: Age, dtype: int64

In [140]:
# membagi data secara custom, misal nilai < 75 adalah nilai tidak lulus
data_dropped['is_children'] = np.where(data_dropped['Age'] < 17, 'Yes', 'No')

data_dropped['age_group'] = np.where(data_dropped['Age'] < 17, 'Children', 'Youngster')
data_dropped['age_group'] = np.where(data_dropped['Age'] >= 40, 'Adult', data_dropped['age_group'])

In [141]:
# data_dropped.loc[data_dropped['is_children'] == 'Yes']
data_dropped.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Embarked_filled,is_children,age_group
274,275,1,3,"Healy, Miss. Hanora ""Nora""",female,37.0,0,0,370375,7.7500,Q,Q,No,Youngster
582,583,0,2,"Downton, Mr. William James",male,54.0,0,0,28403,26.0000,S,S,No,Adult
304,305,0,3,"Williams, Mr. Howard Hugh ""Harry""",male,19.0,0,0,A/5 2466,8.0500,S,S,No,Youngster
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,S,S,No,Youngster
835,836,1,1,"Compton, Miss. Sara Rebecca",female,39.0,1,1,PC 17756,83.1583,C,C,No,Youngster
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.0,0,0,S.O.C. 14879,73.5000,S,S,No,Youngster
718,719,0,3,"McEvoy, Mr. Michael",male,27.0,0,0,36568,15.5000,Q,Q,No,Youngster
333,334,0,3,"Vander Planke, Mr. Leo Edmondus",male,16.0,2,0,345764,18.0000,S,S,Yes,Children
46,47,0,3,"Lennon, Mr. Denis",male,19.0,1,0,370371,15.5000,Q,Q,No,Youngster
48,49,0,3,"Samaan, Mr. Youssef",male,19.0,2,0,2662,21.6792,C,C,No,Youngster

### Transform

In [142]:
# menambah kolom jumlah dari dua nilai
data_dropped['family_size'] = (data_dropped['SibSp'] + data_dropped['Parch'])

In [143]:
# mengubah data ke bentuk lain
data_dropped['sqrd_fare'] = data_dropped['Fare'] ** 2
data_dropped['log_fare'] = np.log(data_dropped['Fare'])

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [144]:
data_dropped.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Embarked_filled,is_children,age_group,family_size,sqrd_fare,log_fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,S,No,Youngster,1,52.562500,1.981001
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C,No,Youngster,1,5081.308859,4.266662
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,S,No,Youngster,0,62.805625,2.070022
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,S,No,Youngster,1,2819.610000,3.972177
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,S,No,Youngster,0,64.802500,2.085672

### Clipping

In [145]:
# membatasi nilai dari 1 - 100
data_dropped['Age'] = data_dropped['Age'].clip(1, 100)

In [146]:
data_dropped['Age'].describe()

count    891.000000
mean      29.584175
std       14.549419
min        1.000000
25%       20.000000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [147]:
# clipping dengan boxplot
Q1 = data_dropped['Fare'].quantile(0.25)
Q3 = data_dropped['Fare'].quantile(0.75)
IQR = Q3 - Q1
Lwishker = Q1 - 1.5 * IQR
Uwishker = Q3 + 1.5 * IQR
data_dropped['clipped_fare'] = data_dropped['Fare'].clip(Lwishker, Uwishker)

In [148]:
data_dropped['clipped_fare'].describe()

count    891.000000
mean      24.046813
std       20.481625
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max       65.634400
Name: clipped_fare, dtype: float64

In [149]:
data_dropped['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

### Scaling

In [150]:
# import sklearn libraries
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# StandardScaler
scaler1 = StandardScaler()
std_scaler = scaler1.fit_transform(data_dropped[['clipped_fare']])

In [151]:
# MinMaxScaler
scaler2 = MinMaxScaler()
mm_scaler = scaler2.fit_transform(data_dropped[['clipped_fare']])

In [152]:
data_dropped['std_fare'] = std_scaler
data_dropped['mm_fare'] = mm_scaler

In [153]:
data_dropped[['clipped_fare', 'std_fare', 'mm_fare']].sample(10, random_state=91)

     clipped_fare  std_fare   mm_fare
535       26.2500  0.107629  0.399943
561        7.8958 -0.789004  0.120300
377       65.6344  2.031623  1.000000
636        7.9250 -0.787578  0.120745
34        65.6344  2.031623  1.000000
79        12.4750 -0.565302  0.190068
430       26.5500  0.122285  0.404513
890        7.7500 -0.796127  0.118078
729        7.9250 -0.787578  0.120745
287        7.8958 -0.789004  0.120300

In [154]:
data_dropped[['clipped_fare', 'std_fare', 'mm_fare']].describe()

       clipped_fare      std_fare     mm_fare
count    891.000000  8.910000e+02  891.000000
mean      24.046813  9.968332e-17    0.366375
std       20.481625  1.000562e+00    0.312056
min        0.000000 -1.174727e+00    0.000000
25%        7.910400 -7.882908e-01    0.120522
50%       14.454200 -4.686152e-01    0.220223
75%       31.000000  3.396748e-01    0.472313
max       65.634400  2.031623e+00    1.000000

### Encoding

In [155]:
data_dropped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PassengerId      891 non-null    int64
 1   Survived         891 non-null    int64
 2   Pclass           891 non-null    int64
 3   Name             891 non-null    object
 4   Sex              891 non-null    object
 5   Age              891 non-null    float64
 6   SibSp            891 non-null    int64
 7   Parch            891 non-null    int64
 8   Ticket           891 non-null    object
 9   Fare             891 non-null    float64
 10  Embarked         891 non-null    object
 11  Embarked_filled  891 non-null    object
 12  is_children      891 non-null    object
 13  age_group        891 non-null    object
 14  family_size      891 non-null    int64
 15  sqrd_fare        891 non-null    float64
 16  log_fare         891 non-null    float64
 17  clipped_fare     891 non-null    float64
 18  std_fare         891 non-null    float64
 19  mm_fare          891 non-null    float64
dtypes: float64(7), int64(6), object(7)
memory usage: 139.3+ KB

In [156]:
col = sorted(data_dropped['Sex'].unique().tolist()) + sorted(data_dropped['Embarked'].unique().tolist()) + sorted(data_dropped['is_children'].unique().tolist())

In [157]:
from sklearn.preprocessing import OneHotEncoder

# membuat variabel enc yang berisi class OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

# mengubah value 'sex' menjadi encoder 1-0
enc_df = pd.DataFrame(enc.fit_transform(data_dropped[['Sex', 'Embarked', 'is_children']]).toarray(),
                      columns=col)

# merge with main df bridge_df on key values
hasil_df = data_dropped[['Sex', 'Embarked', 'is_children']].join(enc_df)
hasil_df

        Sex Embarked is_children  female  male    C    Q    S   No  Yes
0      male        S          No     0.0   1.0  0.0  0.0  1.0  1.0  0.0
1    female        C          No     1.0   0.0  1.0  0.0  0.0  1.0  0.0
2    female        S          No     1.0   0.0  0.0  0.0  1.0  1.0  0.0
3    female        S          No     1.0   0.0  0.0  0.0  1.0  1.0  0.0
4      male        S          No     0.0   1.0  0.0  0.0  1.0  1.0  0.0
..      ...      ...         ...     ...   ...  ...  ...  ...  ...  ...
886    male        S          No     0.0   1.0  0.0  0.0  1.0  1.0  0.0
887  female        S          No     1.0   0.0  0.0  0.0  1.0  1.0  0.0
888  female        S          No     1.0   0.0  0.0  0.0  1.0  1.0  0.0
889    male        C          No     0.0   1.0  1.0  0.0  0.0  1.0  0.0
890    male        Q          No     0.0   1.0  0.0  1.0  0.0  1.0  0.0

[891 rows x 10 columns]

In [158]:
# pandas dummies
dummies = pd.get_dummies(data_dropped[['Sex', 'Embarked', 'is_children']], drop_first=True)
final_data = data_dropped.join(dummies)
dummies.head()

   Sex_male  Embarked_Q  Embarked_S  is_children_Yes
0         1           0           1                0
1         0           0           0                0
2         0           0           1                0
3         0           0           1                0
4         1           0           1                0

## 4. Modelling Preparation

In [159]:
final_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked', 'Embarked_filled', 'is_children',
       'age_group', 'family_size', 'sqrd_fare', 'log_fare', 'clipped_fare',
       'std_fare', 'mm_fare', 'Sex_male', 'Embarked_Q', 'Embarked_S',
       'is_children_Yes'],
      dtype='object')

In [160]:
final_data = final_data.drop(['PassengerId', 'Name', 'Sex', 'Embarked', 'Embarked_filled', 'Ticket', 'is_children'], 1)

<ipython-input-160-aafc38e074ac>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  final_data = final_data.drop(['PassengerId', 'Name', 'Sex', 'Embarked', 'Embarked_filled', 'Ticket', 'is_children'], 1)

In [161]:
# import libraries
from sklearn.model_selection import train_test_split

train, test = train_test_split(final_data, test_size=0.3, random_state=2021)

In [162]:
train.shape, test.shape

((623, 17), (268, 17))

## 5. Modeling

In [166]:
# import libraries
from sklearn.linear_model import LinearRegression
# preidctor = X, target = y

X_train = train.drop(['Fare', 'mm_fare', 'sqrd_fare', 'log_fare', 'clipped_fare', 'std_fare', 'age_group'], 1)
y_train = train['Fare']
X_test = test.drop(['Fare', 'mm_fare', 'sqrd_fare', 'log_fare', 'clipped_fare', 'std_fare', 'age_group'], 1)
y_test = test['Fare']

lr = LinearRegression()
lr.fit(X_train, y_train)

<ipython-input-166-93e899ebb65b>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X_train = train.drop(['Fare', 'mm_fare', 'sqrd_fare', 'log_fare', 'clipped_fare', 'std_fare', 'age_group'], 1)
<ipython-input-166-93e899ebb65b>:7: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X_test = test.drop(['Fare', 'mm_fare', 'sqrd_fare', 'log_fare', 'clipped_fare', 'std_fare', 'age_group'], 1)

LinearRegression()

In [167]:
X_test[2:3]

,Survived,Pclass,Age,SibSp,Parch,family_size,Sex_male,Embarked_Q,Embarked_S,is_children_Yes
666,0,2,25.0,0,0,0,1,0,1,0

In [168]:
lr.predict(X_test[2:3])

array([30.91559742])

In [169]:
# ?LinearRegression